#!/usr/bin/env python3
"""Generate BASELINE_SNAPSHOT.md from configs + LIVE_CONTRACT.md + git state."""

import os
import subprocess
from datetime import datetime

import yaml

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _git(cmd: str) -> str:
    try:
        return subprocess.check_output(f"git {cmd}", shell=True, cwd=BASE, stderr=subprocess.DEVNULL, text=True).strip()
    except Exception:
        return "unknown"


def _fmt_asset_table(assets: dict) -> str:
    lines = [
        "| Asset | Ticker | Allocation | sl_mult | tp_mult |",
        "|---|---|---|---|---|",
    ]
    for name, cfg in sorted(assets.items()):
        lines.append(
            f"| {name} | {cfg['ticker']} | {cfg['allocation']:.1%} | "
            f"{cfg.get('sl_mult', '-')} | {cfg.get('tp_mult', '-')} |"
        )
    return "\n".join(lines)


def main():
    config_path = os.path.join(BASE, "configs", "paper_trading.yaml")
    models_dir = os.path.join(BASE, "paper_trading", "models")

    with open(config_path) as f:
        cfg = yaml.safe_load(f)

    commit_hash = _git("rev-parse --short HEAD")
    commit_date = _git("log -1 --format=%cd --date=short")

    model_files = sorted(f for f in os.listdir(models_dir) if f.endswith(".json")) if os.path.isdir(models_dir) else []

    lines = [
        "# BASELINE SNAPSHOT — AUTO-GENERATED",
        "",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"Commit: {commit_hash} ({commit_date})",
        "Source: `configs/paper_trading.yaml`, `LIVE_CONTRACT.md`",
        "",
        "---",
        "",
        "## 1. SYSTEM CONFIG",
        "",
        "| Parameter | Value |",
        "|---|---|",
        f"| Capital | ${cfg.get('capital', '?'):,} |",
        f"| Position size | {cfg.get('position_size', '?')} |",
        f"| Retrain freq | {cfg.get('retrain_freq', '?')} |",
        f"| Retrain window | {cfg.get('retrain_window', '?')}y |",
        f"| Drawdown limit | {cfg.get('portfolio_drawdown_limit', '?')} |",
        "",
        "---",
        "",
        "## 2. ASSET ALLOCATION",
        "",
        _fmt_asset_table(cfg.get("assets", {})),
        "",
        "---",
        "",
        "## 3. MODEL FILES",
        "",
        f"**Directory:** `paper_trading/models/` — {len(model_files)} `.json` models",
        "",
    ]
    for mf in model_files:
        lines.append(f"- `{mf}`")
    if not model_files:
        lines.append("_(no models found)_")

    lines += [
        "",
        "---",
        "",
        "## 4. EXECUTION GOVERNANCE",
        "",
        "| Layer | State |",
        "|---|---|",
    ]

    exec_cfg = cfg.get("execution", {})
    gov = exec_cfg.get("governance", {})
    narr = gov.get("narrative_config", {})
    liq = gov.get("liquidity_config", {})
    geom = gov.get("regime_geometry", {})

    flip_gate = cfg.get("optimizations", {}).get("regime_conviction_flip_gate", {}).get("enabled", False)
    meta_enabled = bool(cfg.get("meta_labeling", {}).get("confidence_threshold", 0))
    lines.append(f"| Narrative | {'enabled' if narr.get('enabled') else 'disabled'} |")
    lines.append(f"| Liquidity | {'enabled' if liq.get('enabled') else 'disabled'} |")
    lines.append(f"| Regime geometry | {', '.join(geom.keys())} |")
    lines.append(f"| Flip gate | {'enabled' if flip_gate else 'disabled'} |")
    lines.append(f"| Meta-labeling | {'enabled' if meta_enabled else 'disabled'} |")

    opt = cfg.get("optimizations", {})
    lines += [
        "",
        "---",
        "",
        "## 5. OPTIMIZATIONS",
        "",
        "| Optimization | Value |",
        "|---|---|",
        f"| Truncate inference | {opt.get('truncate_inference', '?')} |",
        f"| Batch HTTP | {opt.get('batch_http', '?')} |",
        f"| SQLite state | {opt.get('sqlite_state', '?')} |",
        f"| Async diagnostics | {opt.get('async_diagnostics', '?')} |",
        "",
        "---",
        "",
        "## 6. LIVE_CONTRACT.md REFERENCE",
        "",
        "For full contract details see [`LIVE_CONTRACT.md`](LIVE_CONTRACT.md).",
        "",
        "Key invariants from the contract:",
        "- XGBoost binary classifier with `.json` serialization",
        "- Daily OHLCV from yfinance only",
        "- Triple-barrier labeling with per-asset pt_sl",
        "- Fixed-threshold signal strategy at 0.45",
        "- 15 promoted assets with equal-risk weights",
        "",
        "---",
        "",
        "*This file is auto-generated by `scripts/generate_snapshot.py`. Update via `make snapshot`.*",
        "",
    ]

    out_path = os.path.join(BASE, "BASELINE_SNAPSHOT.md")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"BASELINE_SNAPSHOT.md written ({len(model_files)} models, {len(cfg.get('assets', {}))} assets)")


if __name__ == "__main__":
    main()
